### ISSUE TITLE
SpinalHDL compiler fail

### ISSUE THREAD

**Issue by shengbintai** [SpinalHDL/SpinalWorkshop#1]
peter@ubuntu:~/workspace/SpinalWorkshop$ sbt 
[info] Loading project definition from /home/peter/workspace/SpinalWorkshop/project
[info] Set current project to SpinalWorkshop (in build file:/home/peter/workspace/SpinalWorkshop/)
> run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] workshop.apb3decoder.Apb3DecoderMain
 [2] workshop.blackboxAndClock.MemorySummingMain
 [3] workshop.counter.CounterMain
 [4] workshop.function.FunctionUnitMain
 [5] workshop.function.PrimeMain
 [6] workshop.mandelbrot.PixelSolverMain
 [7] workshop.mandelbrot.PixelSolverMultiCoreMain
 [8] workshop.pwm.ApbPwmMain
 [9] workshop.simcounter.SimCounterTestbench
 [10] workshop.stream.StreamUnitMain
 [11] workshop.timer.Apb3TimerMain
 [12] workshop.timer.TimerMain
 [13] workshop.uart.UartCtrlRxMain
 [14] workshop.udp.UdpAppMain
 [15] workshop.waveplayer.AxiLite4WavePlayerMain
 [16] workshop.waveplayer.AxiLite4WavePlayerMultiTone

Enter number: 12

[info] Running workshop.timer.TimerMain 
[info] [Runtime] SpinalHDL v1.0.5    git head : e15f4b6d197f36d4c98b667167ba1dbf6f271bf6
[info] [Runtime] JVM max memory : 1925.6MiB
[info] [Runtime] Current date : 2017.12.28 18:04:16
[info] [Progress] at 0.000 : Elaborate components
[info] [Progress] at 0.128 : Checks and transforms
[info] 
[info] **********************************************************************************************
[info] [Warning] Elaboration failed (2 errors).
[info]           Spinal will restart with scala trace to help you to find the problem.
[info] **********************************************************************************************
[info] 
[info] [Progress] at 0.218 : Elaborate components
[info] [Progress] at 0.221 : Checks and transforms
[error] Exception in thread "main" spinal.core.SpinalExit: 
[error] 
[error] 
[error]  
[error] ************************************************************************************************************************ 
[error]  ************************************************************************************************************************
[error] 
[error] NO DRIVER ON (toplevel/io_full : out Bool), defined at
[error]     workshop.timer.Timer$$anon$1.<init>(Timer.scala:14)
[error]     workshop.timer.Timer.delayedEndpoint$workshop$timer$Timer$1(Timer.scala:9)
[error]     workshop.timer.Timer$delayedInit$body.apply(Timer.scala:8)
[error]     workshop.timer.Timer.<init>(Timer.scala:8)
[error]     workshop.timer.TimerMain$$anonfun$main$1.apply(TimerMain.scala:11)
[error]     workshop.timer.TimerMain$$anonfun$main$1.apply(TimerMain.scala:11)
[error]     workshop.timer.TimerMain$.main(TimerMain.scala:11)
[error]     workshop.timer.TimerMain.main(TimerMain.scala)
[error] 
[error] 
[error] ************************************************************************************************************************ 
[error]  ************************************************************************************************************************
[error] 
[error] NO DRIVER ON (toplevel/io_value : out UInt[16 bits]), defined at
[error]     workshop.timer.Timer$$anon$1.<init>(Timer.scala:15)
[error]     workshop.timer.Timer.delayedEndpoint$workshop$timer$Timer$1(Timer.scala:9)
[error]     workshop.timer.Timer$delayedInit$body.apply(Timer.scala:8)
[error]     workshop.timer.Timer.<init>(Timer.scala:8)
[error]     workshop.timer.TimerMain$$anonfun$main$1.apply(TimerMain.scala:11)
[error]     workshop.timer.TimerMain$$anonfun$main$1.apply(TimerMain.scala:11)
[error]     workshop.timer.TimerMain$.main(TimerMain.scala:11)
[error]     workshop.timer.TimerMain.main(TimerMain.scala)
[error] 
[error] 
[error] ************************************************************************************************************************ 
[error]  ************************************************************************************************************************
[error] 
[error] Design's errors are listed above.
[error] SpinalHDL compiler exit stack : 
[error] 
[error] 	at spinal.core.SpinalExit$.apply(Misc.scala:355)
[error] 	at spinal.core.SpinalError$.apply(Misc.scala:406)
[error] 	at spinal.core.internals.PhaseContext.checkPendingErrors(Phase.scala:169)
[error] 	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:173)
[error] 	at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$7.apply(Phase.scala:1758)
[error] 	at spinal.core.internals.SpinalVhdlBoot$$anonfun$singleShot$7.apply(Phase.scala:1756)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at spinal.core.internals.SpinalVhdlBoot$.singleShot(Phase.scala:1756)
[error] 	at spinal.core.internals.SpinalVhdlBoot$.apply(Phase.scala:1686)
[error] 	at spinal.core.Spinal$.apply(Spinal.scala:278)
[error] 	at spinal.core.SpinalConfig.generateVhdl(Spinal.scala:132)
[error] 	at workshop.timer.TimerMain$.main(TimerMain.scala:11)
[error] 	at workshop.timer.TimerMain.main(TimerMain.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 9 s, completed Dec 28, 2017 6:04:17 PM

**Comment by Dolu1990** [comment]
Hi,

It is expected, as the workshop come without labs solutions.

See :
[error] NO DRIVER ON (toplevel/io_full : out Bool), defined at
[error] NO DRIVER ON (toplevel/io_value : out UInt[16 bits]), defined at

During compilation, SpinalHDL is doing some checking (lint) on your hardware design, and in the present case, some output signals have no drivers :)

See https://github.com/SpinalHDL/SpinalWorkshop/blob/workshop/src/main/scala/workshop/timer/assets/Timer.solution  for a completted implementation.
(The def driveFrom function isn't required by workshop.timer.TimerMain)

Is this issue ok to be closed ?

**Comment by shengbintai** [comment]
Hi,

Thank you very much, this issue can be closed.
