### ISSUE TITLE
[fix typo]

### ISSUE THREAD

**Issue by chenbo-again** [SpinalHDL/SpinalWorkshop#17]
https://github.com/SpinalHDL/SpinalWorkshop/blob/3a903e741cbbe310a98c75dc1ebbd289cb1c87a4/src/test/scala/workshop/stream/StreamUnitTester.scala#L47

Is there a typo?
It should be 
```
assert(p.toLong == ref, f"rsp had the wrong value from cmdA=$a cmdB=$b%x mem(cmdA)=${ramContent(a)}%x")
```

**Comment by Dolu1990** [comment]
Yes right :)

It is now fixed in the default branch
