### ISSUE TITLE
Is there an error in uart/assets/diagram.png?

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalWorkshop#20]
![image](https://user-images.githubusercontent.com/45759613/221416566-f06517d9-a5bc-4722-a65d-8d43d4df99aa.png)
![image](https://user-images.githubusercontent.com/45759613/221416702-4be589d3-89d3-46ce-98c7-6abdd81062c0.png)

Should io.samplingTick also be connected to the enable terminals of the two previous D Flip-Flop? the code is in File：[uart](https://github.com/SpinalHDL/SpinalWorkshop/tree/workshop/src/main/scala/workshop/uart)/UartCtrlRx.scala
thank you

**Comment by Dolu1990** [comment]
Hi, ahhh the diagram doesn't match the implémentation you are right.
So i would say idealy,  the History range should be 0 until samplingSize, and the 2 first flip flop should be made via  a BufferCC to avoid introducing that inecessary latency (while keeping the metastability protection)

**Comment by LurenAA** [comment]
thank you
