### ISSUE TITLE
Why function "orR" can be used in type scala.collection.immutable.IndexedSeq[spinal.core.Bool]) ?

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalWorkshop#24]
in Prime.solution, 
![image](https://user-images.githubusercontent.com/45759613/227404907-69a1d4b6-b058-42e4-8edd-80dfa9724ee7.png)

the type of "primesHits" is scala.collection.immutable.IndexedSeq[spinal.core.Bool]), I find no function "orR" in scala.collection.immutable.IndexedSeq class of Scala document , in SpinalHDL document orR is only for 
![image](https://user-images.githubusercontent.com/45759613/227405296-7938499d-7d8a-4310-ac87-ce7bb435e016.png)
 .

Why function "orR" can be used in type scala.collection.immutable.IndexedSeq[spinal.core.Bool]) ?  I feel very confused.

**Comment by Dolu1990** [comment]
I think that one come from : 
https://github.com/SpinalHDL/SpinalHDL/blob/48a9b0bd0182786da75c23503eacf3a91913261c/lib/src/main/scala/spinal/lib/Utils.scala#L1072

It is a scala way to extends a pre-existing class with some additional functions.

**Comment by LurenAA** [comment]
thank you
