### ISSUE TITLE
[Question] What software is used to create the diagrams?

### ISSUE THREAD

**Issue by voldemoriarty** [SpinalHDL/SpinalWorkshop#5]
I wanted to know what tool can I use to make the diagrams like the ones in `spec.md` files

**Comment by Dolu1990** [comment]
Hi,

That was made with open office. There is the source : 
https://github.com/SpinalHDL/SpinalDoc/blob/master/asset/diagram.odg

**Comment by voldemoriarty** [comment]
Alright Thanks!
